# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joseph Rosenberg
tagline:          ''
description:      'A place for thoughts and musings about the state of things.'
url:              http://shuhari.io

author:
  name:           'Joseph Rosenberg'
  url:            https://twitter.com/jofus101

paginate:         5

# Custom vars